# Generated by Django 4.0.5 on 2022-06-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApp', '0004_remove_checked_slug_remove_favoris_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='checked',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='todomodel',
            name='favoris',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='favoris',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Checked',
        ),
        migrations.DeleteModel(
            name='Favoris',
        ),
    ]
