# Generated by Django 4.0.5 on 2022-06-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApp', '0006_category_todomodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tâches terminées',
            },
        ),
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favoris', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tâches favorites',
            },
        ),
        migrations.RemoveField(
            model_name='todomodel',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='todomodel',
            name='favoris',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='checked',
            field=models.ManyToManyField(blank=True, to='toDoApp.checked'),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='favoris',
            field=models.ManyToManyField(blank=True, to='toDoApp.favoris'),
        ),
    ]
