# Generated by Django 4.0.5 on 2022-06-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApp', '0008_todomodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='task_details',
            field=models.TextField(blank=True),
        ),
    ]
