# Generated by Django 4.0.5 on 2022-06-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('checked', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('task_details', models.TextField()),
                ('favoris', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tâche',
                'ordering': ['date'],
            },
        ),
    ]
