# Generated by Django 4.0.5 on 2022-06-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favoris', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Favoris',
            },
        ),
        migrations.RemoveField(
            model_name='todomodel',
            name='favoris',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='favoris',
            field=models.ManyToManyField(to='toDoApp.favoris'),
        ),
    ]
