# Generated by Django 4.0.5 on 2022-06-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApp', '0002_favoris_remove_todomodel_favoris_todomodel_favoris'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Tâche terminée',
            },
        ),
        migrations.RemoveField(
            model_name='todomodel',
            name='checked',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='checked',
            field=models.ManyToManyField(to='toDoApp.checked'),
        ),
    ]
